'use strict';

module.exports = {
  PATH_LEFT: 'left',
  PATH_RIGHT: 'right',
  PATH_TOP: 'top',
  PATH_BOTTOM: 'bottom',
  DESIGNER_PAN_HEIGHT: 3000,
  DESIGNER_PAN_WIDTH: 3000,
  NS_SVG: 'http://www.w3.org/2000/svg',
  NS_HTML: 'http://www.w3.org/1999/xhtml',
  TYPES: [
    "bigint",
    "bigserial",
    "bit",
    "bit_varying",
    "boolean",
    "box",
    "bytea",
    "character",
    "character_varying",
    "cidr",
    "circle",
    "date",
    "double",
    "inet",
    "integer",
    "interval",
    "fields",
    "json",
    "jsonb",
    "line",
    "lseg",
    "macaddr",
    "money",
    "numeric",
    "path",
    "pg_lsn",
    "point",
    "polygon",
    "real",
    "smallint",
    "smallserial",
    "serial",
    "text",
    "time",
    "timestamp",
    "tsquery",
    "tsvector",
    "txid_snapshot",
    "uuid",
    "xml"
  ]
};